title: "Laboratory of Cell Ethology"
description: "Digitizing living organisms one cell at a time"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
